var fs = require('fs'),
    tsv = require('tsv'),
    DIR = '../reports/';

exports.readFile = function(name, callback) {
  fs.readFile(DIR + name, 'utf8', function (err, data) {
    if (err) {
     return console.log(err);
    }
    callback(data);
  });
}

exports.writeFile = function(file_name, obj, callback) {
  fs.writeFile(DIR + file_name + '.json', JSON.stringify(obj), function(err) {
    if(err) {
      console.log(err);
    }
  });
  callback();
};

exports.convertJsonToTsv = function(array_json, callback) {

  // sortObjByKey(array_json, function(sorted_array_json) {
  //   callback(tsv.stringify(sorted_array_json));
  // })

}

function sortObjByKey(array_json, callback) {
  var obj = array_json,
      sort = [],
      new_obj = {},
      new_arr = [];

  for (var key in obj) {
    sort.push([key, obj[key]])
  }

  sort = sort.sort(function(a, b) { return b[1] - a[1]; })
  console.log(sort)

  for (var i = 0; i < sort.length; i++) {
    new_obj[sort[i][0]] = sort[i][1];
  };

  callback(new_arr.push(new_obj));
  // return new_arr.push(new_obj);
}

sortObjByKey(arr, function(result) {console.log(result)})

var arr = [ { name: '6_pm_com', total_count: 11 },
  { name: '9_gag_com', total_count: 42 },
  { name: 'aa_com', total_count: 11 },
  { name: 'abcnews_go_com', total_count: 33 },
  { name: 'accuweather_com', total_count: 57 },
  { name: 'agoda_com', total_count: 32 },
  { name: 'alibaba_com', total_count: 5 },
  { name: 'allrecipes_com', total_count: 44 },
  { name: 'amazon_co_uk', total_count: 2 },
  { name: 'amazon_com', total_count: 2 },
  { name: 'americanexpress_com', total_count: 13 },
  { name: 'ancestry_com', total_count: 7 },
  { name: 'answers_yahoo_com', total_count: 0 },
  { name: 'apple_com', total_count: 0 },
  { name: 'archive_org', total_count: 0 },
  { name: 'ask_com', total_count: 7 },
  { name: 'ausopen_com', total_count: 24 },
  { name: 'autodesk_com', total_count: 23 },
  { name: 'babycenter_com', total_count: 28 },
  { name: 'bankofamerica_com', total_count: 9 },
  { name: 'bankrate_com', total_count: 34 },
  { name: 'battle_net', total_count: 6 },
  { name: 'bbb_org', total_count: 19 },
  { name: 'bbc_co_uk', total_count: 0 },
  { name: 'bbc_co_uk_news', total_count: 0 },
  { name: 'bbc_co_uk_sport_0_football', total_count: 0 },
  { name: 'berkeley_edu', total_count: 5 },
  { name: 'bestbuy_com', total_count: 8 },
  { name: 'biblegateway_com', total_count: 8 },
  { name: 'bing_com', total_count: 0 },
  { name: 'blackboard_com', total_count: 14 },
  { name: 'bleacherreport_com', total_count: 16 },
  { name: 'blockchain_info', total_count: 0 },
  { name: 'bloomberg_com', total_count: 2 },
  { name: 'boardgamegeek_com', total_count: 11 },
  { name: 'bodybuilding_com', total_count: 19 },
  { name: 'bom_gov_au', total_count: 15 },
  { name: 'booking_com', total_count: 40 },
  { name: 'brainyquote_com', total_count: 14 },
  { name: 'capitalone_com', total_count: 8 },
  { name: 'cbssports_com', total_count: 56 },
  { name: 'cdc_gov', total_count: 8 },
  { name: 'change_org', total_count: 9 },
  { name: 'https_www_chase_com', total_count: 8 },
  { name: 'chess_com', total_count: 13 },
  { name: 'cnbc_com', total_count: 171 },
  { name: 'cnn_com', total_count: 62 },
  { name: 'codecademy_com', total_count: 5 },
  { name: 'complex_com', total_count: 71 },
  { name: 'correios_com_br', total_count: 3 },
  { name: 'cosmopolitan_com', total_count: 11 },
  { name: 'costco_com', total_count: 5 },
  { name: 'coupons_com', total_count: 8 },
  { name: 'coursera_org', total_count: 1 },
  { name: 'cracked_com', total_count: 118 },
  { name: 'cricbuzz_com', total_count: 14 },
  { name: 'css_tricks_com', total_count: 8 },
  { name: 'dailykos_com', total_count: 82 },
  { name: 'deadspin_com', total_count: 0 },
  { name: 'delta_com', total_count: 17 },
  { name: 'developer_android_com', total_count: 3 },
  { name: 'deviantart_com', total_count: 7 },
  { name: 'dict_cc', total_count: 3 },
  { name: 'digg_com', total_count: 21 },
  { name: 'digitaltrends_com', total_count: 41 },
  { name: 'dorkly_com', total_count: 21 },
  { name: 'dpreview_com', total_count: 17 },
  { name: 'drugs_com', total_count: 13 },
  { name: 'duolingo_com', total_count: 5 },
  { name: 'ea_com', total_count: 6 },
  { name: 'easyjet_com', total_count: 50 },
  { name: 'ebay_com', total_count: 27 },
  { name: 'economictimes_indiatimes_com', total_count: 118 },
  { name: 'economist_com', total_count: 68 },
  { name: 'ehow_com', total_count: 9 },
  { name: 'elsevier_com', total_count: 6 },
  { name: 'en_wikipedia_org', total_count: 0 },
  { name: 'en_wikipedia_org_wiki_main_page', total_count: 0 },
  { name: 'engadget_com', total_count: 24 },
  { name: 'espn_go_com', total_count: 37 },
  { name: 'espn_go_com_nfl', total_count: 43 },
  { name: 'espncricinfo_com', total_count: 41 },
  { name: 'espnfc_com', total_count: 11 },
  { name: 'https_www_etsy_com', total_count: 4 },
  { name: 'europa_eu', total_count: 0 },
  { name: 'expedia_com', total_count: 14 },
  { name: 'facebook_com', total_count: 0 },
  { name: 'fedex_com', total_count: 0 },
  { name: 'finance_yahoo_com', total_count: 31 },
  { name: 'food_com', total_count: 36 },
  { name: 'fool_com', total_count: 84 },
  { name: 'forbes_com', total_count: 150 },
  { name: 'foxnews_com', total_count: 43 },
  { name: 'freelotto_com', total_count: 5 },
  { name: 'gamefaqs_com', total_count: 22 },
  { name: 'gamespot_com', total_count: 88 },
  { name: 'gap_com', total_count: 63 },
  { name: 'gizmodo_com', total_count: 0 },
  { name: 'goal_com', total_count: 0 },
  { name: 'goodreads_com', total_count: 11 },
  { name: 'google_com', total_count: 0 },
  { name: 'grantland_com', total_count: 26 },
  { name: 'groupon_com', total_count: 2 },
  { name: 'gsmarena_com', total_count: 12 },
  { name: 'harvard_edu', total_count: 13 },
  { name: 'hdfcbank_com', total_count: 7 },
  { name: 'hgtv_com', total_count: 8 },
  { name: 'health_com', total_count: 44 },
  { name: 'hm_com', total_count: 8 },
  { name: 'hilton_com', total_count: 215 },
  { name: 'homedepot_com', total_count: 53 },
  { name: 'hotels_com', total_count: 49 },
  { name: 'howstuffworks_com', total_count: 19 },
  { name: 'hulu_com', total_count: 0 },
  { name: 'huffingtonpost_com', total_count: 164 },
  { name: 'icicibank_com', total_count: 4 },
  { name: 'ieee_org', total_count: 8 },
  { name: 'ign_com', total_count: 85 },
  { name: 'ign_com_wikis', total_count: 54 },
  { name: 'ikea_com', total_count: 1 },
  { name: 'imdb_com', total_count: 35 },
  { name: 'imgur_com', total_count: 10 },
  { name: 'indeed_com', total_count: 10 },
  { name: 'individual_com', total_count: 11 },
  { name: 'instructables_com', total_count: 12 },
  { name: 'irs_gov', total_count: 2 },
  { name: 'investopedia_com', total_count: 58 },
  { name: 'jalopnik_com', total_count: 3 },
  { name: 'jma_go_jp', total_count: 0 },
  { name: 'jstor_org', total_count: 2 },
  { name: 'jw_org', total_count: 0 },
  { name: 'https_www_kaiserpermanente_org', total_count: 4 },
  { name: 'kayak_com', total_count: 3 },
  { name: 'khanacademy_org', total_count: 3 },
  { name: 'kohls_com', total_count: 104 },
  { name: 'kongregate_com', total_count: 16 },
  { name: 'leagueoflegends_com', total_count: 4 },
  { name: 'legacy_com', total_count: 5 },
  { name: 'lego_com', total_count: 1 },
  { name: 'linkedin_com', total_count: 10 },
  { name: 'livejournal_com', total_count: 20 },
  { name: 'livescore_com', total_count: 6 },
  { name: 'macys_com', total_count: 31 },
  { name: 'mail_google_com', total_count: 0 },
  { name: 'mail_live_com', total_count: 6 },
  { name: 'mail_yahoo_com', total_count: 4 },
  { name: 'marketwatch_com', total_count: 104 },
  { name: 'marriott_com', total_count: 38 },
  { name: 'match_com', total_count: 30 },
  { name: 'mayoclinic_org', total_count: 12 },
  { name: 'medicinenet_com', total_count: 0 },
  { name: 'medscape_com', total_count: 32 },
  { name: 'mensfitness_com', total_count: 39 },
  { name: 'menshealth_com', total_count: 65 },
  { name: 'mercola_com', total_count: 20 },
  { name: 'microsoft_com', total_count: 6 },
  { name: 'merriam_webster_com', total_count: 70 },
  { name: 'minecraftforum_net', total_count: 278 },
  { name: 'miniclip_com', total_count: 22 },
  { name: 'https_www_mint_com', total_count: 7 },
  { name: 'mit_edu', total_count: 4 },
  { name: 'mlb_mlb_com', total_count: 28 },
  { name: 'money_cnn_com', total_count: 113 },
  { name: 'msn_com', total_count: 2 },
  { name: 'myfitnesspal_com', total_count: 15 },
  { name: 'nationalgeographic_com', total_count: 24 },
  { name: 'nature_com', total_count: 20 },
  { name: 'nba_com', total_count: 86 },
  { name: 'nbcnews_com', total_count: 23 },
  { name: 'nbcsports_com', total_count: 69 },
  { name: 'ncbi_nlm_nih_gov', total_count: 0 },
  { name: 'ncbi_nlm_nih_gov_pmc', total_count: 0 },
  { name: 'ncbi_nlm_nih_gov_pubmed', total_count: 0 },
  { name: 'netflix_com', total_count: 1 },
  { name: 'ndtv_com', total_count: 108 },
  { name: 'news_google_com', total_count: 0 },
  { name: 'newegg_com', total_count: 80 },
  { name: 'news_yahoo_com', total_count: 9 },
  { name: 'nfl_com', total_count: 59 },
  { name: 'nhl_com', total_count: 56 },
  { name: 'nhs_uk', total_count: 6 },
  { name: 'nike_com', total_count: 0 },
  { name: 'nih_gov', total_count: 6 },
  { name: 'nintendo_com', total_count: 0 },
  { name: 'nlm_nih_gov', total_count: 2 },
  { name: 'nlm_nih_gov_medlineplus', total_count: 5 },
  { name: 'noaa_gov', total_count: 8 },
  { name: 'nordstrom_com', total_count: 36 },
  { name: 'npr_org', total_count: 15 },
  { name: 'office_com', total_count: 0 },
  { name: 'nytimes_com', total_count: 144 },
  { name: 'opentable_com', total_count: 9 },
  { name: 'orbitz_com', total_count: 5 },
  { name: 'overstock_com', total_count: 53 },
  { name: 'pandora_com', total_count: 5 },
  { name: 'patents_uspto_gov', total_count: 0 },
  { name: 'patient_co_uk', total_count: 47 },
  { name: 'paypal_com', total_count: 2 },
  { name: 'pcgamer_com', total_count: 138 },
  { name: 'pch_com', total_count: 26 },
  { name: 'pinterest_com', total_count: 7 },
  { name: 'phonearena_com', total_count: 184 },
  { name: 'playstation_com', total_count: 6 },
  { name: 'plus_google_com', total_count: 0 },
  { name: 'pogo_com', total_count: 30 },
  { name: 'post_japanpost_jp', total_count: 3 },
  { name: 'premierleague_com', total_count: 208 },
  { name: 'prevention_com', total_count: 223 },
  { name: 'priceline_com', total_count: 5 },
  { name: 'profootballtalk_nbcsports_com', total_count: 90 },
  { name: 'psychologytoday_com', total_count: 12 },
  { name: 'reddit_com', total_count: 9 },
  { name: 'researchgate_net', total_count: 1 },
  { name: 'reuters_com', total_count: 151 },
  { name: 'reverso_net', total_count: 59 },
  { name: 'roblox_com', total_count: 4 },
  { name: 'rottentomatoes_com', total_count: 31 },
  { name: 'ryanair_com', total_count: 2 },
  { name: 'salon_com', total_count: 30 },
  { name: 'samsung_com', total_count: 50 },
  { name: 'sbnation_com', total_count: 59 },
  { name: 'sciencedirect_com', total_count: 4 },
  { name: 'scribd_com', total_count: 9 },
  { name: 'search_yahoo_com', total_count: 0 },
  { name: 'sears_com', total_count: 61 },
  { name: 'shutterstock_com', total_count: 12 },
  { name: 'siteadvisor_com', total_count: 0 },
  { name: 'si_com', total_count: 30 },
  { name: 'sitepoint_com', total_count: 6 },
  { name: 'skype_com', total_count: 2 },
  { name: 'skysports_com', total_count: 25 },
  { name: 'slashdot_org', total_count: 129 },
  { name: 'slate_com', total_count: 42 },
  { name: 'southwest_com', total_count: 9 },
  { name: 'sports_yahoo_com', total_count: 5 },
  { name: 'spotify_com', total_count: 5 },
  { name: 'stackoverflow_com', total_count: 9 },
  { name: 'stanford_edu', total_count: 2 },
  { name: 'staples_com', total_count: 63 },
  { name: 'state_gov', total_count: 5 },
  { name: 'store_steampowered_com', total_count: 0 },
  { name: 'stumbleupon_com', total_count: 14 },
  { name: 'sulekha_com', total_count: 5 },
  { name: 'target_com', total_count: 8 },
  { name: 'techcrunch_com', total_count: 64 },
  { name: 'ted_com', total_count: 6 },
  { name: 'thefreedictionary_com', total_count: 1 },
  { name: 'theguardian_com', total_count: 0 },
  { name: 'theguardian_com_technology', total_count: 0 },
  { name: 'theguardian_com_world', total_count: 13 },
  { name: 'theonion_com', total_count: 33 },
  { name: 'thesaurus_com', total_count: 17 },
  { name: 'theverge_com', total_count: 69 },
  { name: 'time_com', total_count: 32 },
  { name: 'timeanddate_com', total_count: 1 },
  { name: 'timeanddate_com_worldclock', total_count: 1 },
  { name: 'tomshardware_com', total_count: 0 },
  { name: 'tmz_com', total_count: 110 },
  { name: 'translate_google_com', total_count: 1 },
  { name: 'tripadvisor_com', total_count: 16 },
  { name: 'tumblr_com', total_count: 5 },
  { name: 'twitch_tv', total_count: 18 },
  { name: 'twitter_com_nbctheevent', total_count: 1 },
  { name: 'udemy_com', total_count: 2 },
  { name: 'ups_com', total_count: 0 },
  { name: 'united_com', total_count: 84 },
  { name: 'urbandictionary_com', total_count: 6 },
  { name: 'usatoday_com', total_count: 29 },
  { name: 'vrbo_com', total_count: 6 },
  { name: 'w3_org', total_count: 0 },
  { name: 'walmart_com', total_count: 23 },
  { name: 'washingtonpost_com', total_count: 44 },
  { name: 'weather_com', total_count: 5 },
  { name: 'weather_gov', total_count: 2 },
  { name: 'webmd_com', total_count: 14 },
  { name: 'weebly_com', total_count: 55 },
  { name: 'weightwatchers_com', total_count: 14 },
  { name: 'wellsfargo_com', total_count: 0 },
  { name: 'who_int', total_count: 2 },
  { name: 'whitepages_com', total_count: 35 },
  { name: 'wiktionary_org', total_count: 0 },
  { name: 'williamhill_com', total_count: 14 },
  { name: 'wordpress_com', total_count: 4 },
  { name: 'wordreference_com', total_count: 2 },
  { name: 'wowhead_com', total_count: 132 },
  { name: 'wsj_com', total_count: 119 },
  { name: 'wwe_com', total_count: 90 },
  { name: 'xbox_com', total_count: 8 },
  { name: 'xe_com', total_count: 29 },
  { name: 'y8_com', total_count: 21 },
  { name: 'yahoo_com', total_count: 0 },
  { name: 'yahoo_com_health', total_count: 3 },
  { name: 'yellowpages_com', total_count: 35 },
  { name: 'yelp_com', total_count: 16 },
  { name: 'youtube_com', total_count: 4 },
  { name: 'zillow_com', total_count: 8 },
  { name: 'zomato_com', total_count: 8 } ]